version: '3.3'
services:
    pagermon-client:
        build:
            context: https://github.com/blackwellj/pagermon-client.git
            dockerfile: Dockerfile
        container_name: pagermon-client
        image: pagermon-client:latest
        restart: unless-stopped
        environment:
            - TZ=Europe/London
        volumes:
            - '${HOME}/pagermon/client:/pagermon/client/config'
        devices:
            - /dev/bus/usb
        network_mode: host
